# Este archivo le dice a Gitpod cómo configurar el entorno de desarrollo.
# Debe estar en la raíz de tu repositorio.

# Tareas que se ejecutan al iniciar el espacio de trabajo.
tasks:
  - name: Instalar Dependencias y Configurar Base de Datos
    init: |
      # Espera a que MySQL esté listo.
      gp await-port 3306
      # Instala las dependencias de PHP.
      composer install
      # Crea la base de datos 'rollxpress' y la tabla de usuarios (si no existen).
      mysql -u root -e "CREATE DATABASE IF NOT EXISTS rollxpress; USE rollxpress; CREATE TABLE IF NOT EXISTS usuarios (id INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(255), email VARCHAR(255), password VARCHAR(255), rol VARCHAR(50));"
    command: |
      # Muestra un mensaje de bienvenida.
      echo "Entorno listo. Inicia el servidor con: php -S 0.0.0.0:8080"

# Puertos que Gitpod debe exponer.
ports:
  # Puerto para el servidor web.
  - port: 8080
    onOpen: open-preview
  # Puerto para MySQL.
  - port: 3306
    onOpen: ignore

# Configuración de Docker para incluir PHP y MySQL.
image:
  file: .gitpod.Dockerfile
